### PR TITLE
Django 1.7 support

### PR DESCRIPTION
**Pull request by last-partizan**
Here is what needed to support django-1.7

also, removed django-debug toolbar from requirements.

### CODE REVIEW

**Comment by rozza** [comment]
@last-partizan this currently isnt passing - I've not looked why.

This repo is not really maintained - hence the readme.  I have invited you as a collaborator in the hope that you can help and one day this repo will be useful to others!

**Comment by last-partizan** [comment]
It's failed for python 2.6, becouse someone used set definition syntax `a = {1,2,3}` from python 2.7.
Can we drop python 2.6 support? or i'll fix this

For python 2.7 it's failed becouse incorrect test project settings, i'll try to investigate further.

**Comment by avelino** [comment]
I think we should have python 2.6 support

**Comment by last-partizan** [comment]
Today i've got time to investigate test process. Here is results:

- with python 2.6 build was failing becouse latest django doesn't support that python version. Fixed by configuring travis to use different requirements file for 2.6, which uses django 1.6
- with python 2.7 build was failing becouse incorrect django test database settings. Fixed by using in-memory sqlitedb

Tests still failing, becouse looks like they never passed.
Now i will merge pull request and maybe later someone fix the tests.

**Pull request merged**
