### PR TITLE
Python3 syntax support

### PR DESCRIPTION
**Pull request by Alex131089**
If you're interested, basic modifications for python3 support (don't know if it breaks python2 support).

Can't get the example to be working, stuck with : 
```
  File "/srv/emma/pymodules/django-mongoengine_perso/example/tumblelog/tumblelog/admin.py", line 26, in <module>
    admin.site.register(BlogPost, BlogPostAdmin)
  File "/srv/emma/pymodules/django-mongoengine_perso/django_mongoengine/mongo_admin/sites.py", line 100, in register
    validate(admin_class, model)
  File "/srv/emma/pymodules/django-mongoengine_perso/django_mongoengine/mongo_admin/validation.py", line 24, in validate
    _validate(cls, model)
  File "/srv/emma/pymodules/django-mongoengine_perso/django_mongoengine/mongo_admin/validation.py", line 38, in _validate
    validate_base(cls, model)
  File "/srv/emma/pymodules/django-mongoengine_perso/django_mongoengine/mongo_admin/validation.py", line 315, in validate_base
    "BaseModelForm." % cls.__name__)
django.core.exceptions.ImproperlyConfigured: BlogPostAdmin.form does not inherit from BaseModelForm.
```
Which seems to be related to something not implemented (DocumentModelForm ?).

### CODE REVIEW

**Comment by Alex131089** [comment]
Documentation about changes : 

https://stackoverflow.com/questions/4364565/replacing-the-new-module
https://stackoverflow.com/questions/2827623/python-create-object-and-add-attributes-to-it

https://stackoverflow.com/questions/15712210/python-3-2-lambda-syntax-error
http://www.python.org/dev/peps/pep-3113/

https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.encoding.force_text

**Comment by Alex131089** [comment]
https://stackoverflow.com/questions/13013638/python-cannot-handle-numbers-string-starting-with-0-why : 
01, 05, .. : they seems to be considered as octal (probably not hurting, but probably not what you want either)

**Comment by last-partizan** [comment]
Looks good, i just changed `patch document` to
```
def patch_document(function, instance):
    setattr(instance, function.__name__, partial(function, instance)) 
```

becouse your wariant doesn't seems to work.

**Comment by last-partizan** [comment]
Btw, with python2.7 i don't get that error:
```
django.core.exceptions.ImproperlyConfigured: BlogPostAdmin.form does not inherit from BaseModelForm.
```

Test project is running fine. (Just forms not rendered at all, but i'm working on it)

**Comment by last-partizan** [comment]
Fixed that error.

**Pull request merged**
